name             "opsworks_env"
maintainer       "Barry Hoggard"
maintainer_email "barry@tristanmedia.com"
license          "MIT"
description      "Chef cookbook to write out /etc/profile.d file based on and OpsWorks stack's custom JSON"
version          "0.1.2"
